### ISSUE TITLE
Windows 7 "Django Click" not allowing the "shift+9" key "(". 

### ISSUE THREAD

**Issue by chavenor** [kahi/sublime-django-click#4]
Following the installation of "Django Click" I was unable to use the "(" char. 

Below is a log of me starting Sublime and installing django-click. 
Let me know if you need me to retest.  Thanks

```
startup, version: 2221 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 2/sublime_text.exe
working dir: /C/ProgramData/Microsoft/Windows/Start Menu/Programs
packages path: /C/Users/Casey/AppData/Roaming/Sublime Text 2/Packages
settings path: /C/Users/Casey/AppData/Roaming/Sublime Text 2/Settings
PackageSetup not required
Py_GetProgramName(): sublime_text.exe
Py_GetExecPrefix(): C:\Program Files\Sublime Text 2
Py_GetProgramFullPath(): C:\Program Files\Sublime Text 2\sublime_text.exe
Py_GetPath(): C:\Program Files\Sublime Text 2\python26.zip;C:\Program Files\Sublime Text 2\DLLs;C:\Program Files\Sublime Text 2\lib;C:\Program Files\Sublime Text 2\lib\plat-win;C:\Program Files\Sublime Text 2\lib\lib-tk;C:\Program Files\Sublime Text 2
Py_GetPythonHome(): C:\Program Files\Sublime Text 2
catalogue loaded
found 9 files for base name Default.sublime-keymap
found 2 files for base name Default.sublime-mousemap
found 7 files for base name Main.sublime-menu
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\BracketHighlighter\bh_core.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\BracketHighlighter\bh_plugin.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\BracketHighlighter\bh_remove.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\BracketHighlighter\bh_swapping.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\BracketHighlighter\bh_wrapping.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\BracketHighlighter\ure.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\CSS\css_completions.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\comment.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\copy_path.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\delete_word.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\detect_indentation.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\duplicate_line.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\echo.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\exec.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\fold.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\font.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\goto_line.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\indentation.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\kill_ring.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\mark.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\new_templates.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\open_file_settings.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\open_in_browser.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\paragraph.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\save_on_focus_lost.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\scroll.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\set_unsaved_view_name.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\side_bar.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\sort.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\swap_line.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\switch_file.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\transform.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\transpose.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Default\trim_trailing_white_space.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Diff\diff.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Emmet\emmet-plugin.py
Emmet: No need to update PyV8
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\HTML\encode_html_entities.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\HTML\html_completions.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Jedi - Python autocompletion\console_logging.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Jedi - Python autocompletion\jedi_daemon.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Jedi - Python autocompletion\python_go_to.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Jedi - Python autocompletion\sublime_jedi.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Jedi - Python autocompletion\utils.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Package Control\Package Control.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Pretty JSON\PrettyJson.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\SublimeLinter\SublimeLinter.py
imported capp_lint
imported pep8
imported pyflakes
imported pyflakes.api
imported pyflakes.checker
imported pyflakes.messages
imported pyflakes.reporter
SublimeLinter: C loaded
SublimeLinter: CoffeeScript loaded
SublimeLinter: CSS loaded
SublimeLinter: c_cpplint loaded
SublimeLinter: Git Commit Message loaded
SublimeLinter: Ruby Haml loaded
SublimeLinter: haskell loaded
SublimeLinter: HTML loaded
SublimeLinter: Java loaded
SublimeLinter: JavaScript loaded
SublimeLinter: Lua loaded
SublimeLinter: Annotations loaded
SublimeLinter: Objective-J loaded
SublimeLinter: Perl loaded
SublimeLinter: PHP loaded
SublimeLinter: Puppet loaded
SublimeLinter: Python loaded
SublimeLinter: ruby-lint loaded
SublimeLinter: Ruby loaded
SublimeLinter: pylint loaded
SublimeLinter: XML loaded
plugin init time: 0.262048
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.376963
SublimeLinter: python enabled (built in)
wrote startup cache, added files: 2 orphaned files: 2 total files: 113 cache hits: 111
startup time: 0.453191 (package setup was not run)
loaded 837 snippets
Package Control: Skipping automatic upgrade, last run at 2013-10-25 07:20:54, next run at 2013-10-25 08:20:54 or after
An exception occured when running pep8 checker: 'int' object has no attribute 'lineno'
ignored packages updated to: [Vintage, Django Click]
found 1 files for base name Default.sublime-theme
reloading /C/Users/Casey/AppData/Roaming/Sublime Text 2/Packages/User/Preferences.sublime-settings
theme loaded
found 1 files for base name Default.sublime-theme
theme loaded
ignored packages updated to: [Vintage]
found 1 files for base name Default.sublime-theme
reloading /C/Users/Casey/AppData/Roaming/Sublime Text 2/Packages/User/Package Control.sublime-settings
reloading /C/Users/Casey/AppData/Roaming/Sublime Text 2/Packages/User/Preferences.sublime-settings
theme loaded
found 1 files for base name Default.sublime-theme
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Django Click\__init__.py
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Django Click\django_click.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
    m = imp.load_module(modulename, *m_info)
  File ".\django_click.py", line 6, in <module>
    from .utils import parse_tag
ValueError: Attempted relative import in non-package
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Django Click\tests.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
    m = imp.load_module(modulename, *m_info)
  File ".\tests.py", line 6, in <module>
    from .utils import parse_tag
ValueError: Attempted relative import in non-package
Reloading plugin C:\Users\Casey\AppData\Roaming\Sublime Text 2\Packages\Django Click\utils.py
found 10 files for base name Default.sublime-keymap
found 3 files for base name Default.sublime-mousemap
theme loaded
context must be an array
loading pointer bindings
```

**Comment by kahi** [comment]
Sorry, I couldn't emulate the problem in ST2@Mac.

Are you sure this issue disappears after deactivating Django Click package?

**Comment by chavenor** [comment]
I was able to repeat this event.   I'll try to take a look at this and get
back to you if I can figure out what's happening.

Thanks for getting back to me.
